# Generated by Django 3.1.1 on 2021-12-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('extra_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('address', models.CharField(default=None, max_length=100)),
                ('inventory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to='apartments')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
            ],
            options={
                'db_table': 'apartment_image',
            },
        ),
        migrations.CreateModel(
            name='ApartmentExtraService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment')),
                ('extra_service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='extra_services.extraservice')),
            ],
            options={
                'db_table': 'apartment_extra_service',
            },
        ),
    ]
