# Generated by Django 3.1.1 on 2021-12-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'extra_service_category',
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('extra_service_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='extra_services.extraservicecategory')),
            ],
            options={
                'db_table': 'extra_service',
            },
        ),
    ]
